# Travis CI configuration file

language: python
dist: trusty
python:
  - 3.6
virtualenv:
    system_site_package: true
script:
    - pip install -r ./requirements.txt
    - python -m unittest discover
    - make